version: 2
updates:
  - directory: /
    package-ecosystem: npm
    rebase-strategy: auto
    reviewers:
      - NoamGaash
    commit-message:
      prefix: "[dependabot]"
    schedule:
      interval: weekly
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
